use rbac_macro::{Namespace, Role};
use rbac::{ACNamespace, ACRole};

// This file is generated by rbac-parser

#[derive(Role, Clone, Debug)]
#[role_subject(Namespace::User)]
#[role_object(Namespace::Post)]
pub enum UserToPost {
    Writer,
    #[subrole_of(Writer)]
    Viewer,
}

#[derive(Role, Clone, Debug)]
#[role_subject(Namespace::User)]
#[role_object(Namespace::Group)]
pub enum UserToGroup {
    Admin,
    #[subrole_of(Admin)]
    Member,
}

#[derive(Role, Clone, Debug)]
#[role_subject(Namespace::Group)]
#[role_object(Namespace::Post)]
pub enum GroupToPost {
    Writer,
    #[subrole_of(Writer)]
    Viewer,
}

#[derive(Namespace, Debug, Clone)]
pub enum Namespace {
    User,
    #[namespace_role(UserToPost::Writer)]
    #[namespace_role(UserToPost::Viewer)]
    #[namespace_role(GroupToPost::Writer)]
    #[namespace_role(GroupToPost::Viewer)]
    Post,
    #[namespace_role(UserToGroup::Admin)]
    #[namespace_role(UserToGroup::Member)]
    Group,
}

// Above is generated by rbac-parser