use std::collections::HashMap;

use codegen::{Enum, Scope, Variant};
use serde_json::{self, Value};

mod error;

struct Namespace {
    name: String,
    objects: Vec<Object>,
}

struct Object {
    name: String,
    roles: Vec<Role>,
}

struct Role {
    name: String,
    subroles: Vec<String>,
}

fn is_pascal_case(s: &str) -> bool {
    !s.is_empty() && s.chars().next().unwrap().is_ascii_uppercase()
}

fn validate(parsed: &Vec<Namespace>) -> Result<(), error::ParserError> {
    let mut namespaces: Vec<String> = Vec::new();

    for namespace in parsed.iter() {
        if !is_pascal_case(&namespace.name) {
            return Err(error::ParserError::SyntaxError(
                "Namespace name is not in PascalCase".to_string(),
            ));
        }

        namespaces.push(namespace.name.clone());
    }

    for namespace in parsed.iter() {
        for object in namespace.objects.iter() {
            if !namespaces.contains(&object.name) {
                return Err(error::ParserError::SyntaxError(
                    "Namespace.Object name is not valid".to_string(),
                ));
            }

            let mut roles: Vec<String> = Vec::new();
            for role in object.roles.iter() {
                if !is_pascal_case(&role.name) {
                    return Err(error::ParserError::SyntaxError(
                        "Role name is not in PascalCase".to_string(),
                    ));
                }

                roles.push(role.name.clone());
            }

            for role in object.roles.iter() {
                for subrole in role.subroles.iter() {
                    if !roles.contains(subrole) {
                        return Err(error::ParserError::SyntaxError(
                            "Role.Subrole name is not valid".to_string(),
                        ));
                    }
                }
            }
        }
    }

    Ok(())
}

pub fn parse(file_path: &str) -> Result<String, error::ParserError> {
    let file = std::fs::read_to_string(file_path)?;
    let namespaces: Value = serde_json::from_str(&file)?;

    let parsed: Vec<Namespace> = namespaces
        .as_array()
        .unwrap()
        .iter()
        .map(|namespace| {
            let name = namespace["name"].as_str().unwrap();

            let parse_object = |object: &Value| {
                let name = object["name"].as_str().unwrap();
                let roles = object["roles"].as_array().unwrap();

                let parsed_roles: Vec<Role> = roles
                    .iter()
                    .map(|role| {
                        let name = role["name"].as_str().unwrap();

                        Role {
                            name: name.to_string(),
                            subroles: match role["subroles"].as_array() {
                                Some(subroles) => subroles
                                    .iter()
                                    .map(|subrole| subrole.as_str().unwrap().to_string())
                                    .collect(),
                                None => Vec::new(),
                            },
                        }
                    })
                    .collect();

                Object {
                    name: name.to_string(),
                    roles: parsed_roles,
                }
            };
            let objects = match namespace["objects"].as_array() {
                Some(objects) => objects.iter().map(parse_object).collect(),
                None => Vec::new(),
            };

            Namespace {
                name: name.to_string(),
                objects,
            }
        })
        .collect();

    validate(&parsed)?;

    let mut scope = Scope::new();
    scope.raw("// This file is generated by rbac-parser");
    scope.import("rbac_macro", "{Namespace, Role}");
    scope.import("rbac", "{ACNamespace, ACRole}");

    let mut namespace = Enum::new("Namespace");
    namespace.vis("pub");
    namespace.derive("Namespace");
    namespace.derive("Debug");
    namespace.derive("Clone");

    let mut roles_to_object: HashMap<String, Vec<String>> = HashMap::new();

    for value in parsed.iter() {
        for object in value.objects.iter() {
            let role_enum_name = format!("{}To{}", value.name, object.name);
            let entry = roles_to_object
                .entry(object.name.clone())
                .or_insert(Vec::new());

            for role in object.roles.iter() {
                entry.push(format!("{}::{}", role_enum_name, role.name));
            }
        }
    }

    for value in parsed.iter() {
        let mut variant = Variant::new(value.name.clone());
        let mut subset_ofs: HashMap<String, Vec<String>> = HashMap::new();

        for object in value.objects.iter() {
            for role in object.roles.iter() {
                for subrole in role.subroles.iter() {
                    let key = format!("{}_{}", object.name, subrole);
                    let subset_of = subset_ofs.entry(key).or_insert(Vec::new());
                    subset_of.push(role.name.clone());
                }
            }
        }

        for object in value.objects.iter() {
            let role_enum_name = format!("{}To{}", value.name, object.name);
            let mut role_enum = Enum::new(role_enum_name.clone());
            role_enum.vis("pub");
            role_enum.derive("Role");
            role_enum.derive("Clone");
            role_enum.derive("Debug");
            role_enum.r#macro(&format!("#[role_subject(Namespace::{})]", value.name));
            role_enum.r#macro(&format!("#[role_object(Namespace::{})]", object.name));

            for role in object.roles.iter() {
                // variant.annotation(format!(
                //     "#[namespace_role({}::{})]",
                //     role_enum_name, role.name
                // ));

                let mut variant = Variant::new(role.name.clone());

                let key = format!("{}_{}", object.name, role.name);
                if subset_ofs.contains_key(&key) {
                    let subset_of = subset_ofs.get(&key).unwrap();
                    for superrole in subset_of.iter() {
                        variant.annotation(format!("#[subrole_of({})]", superrole));
                    }
                }

                role_enum.push_variant(variant);
            }

            scope.push_enum(role_enum);
        }

        if let Some(roles) = roles_to_object.get(&value.name) {
            for role in roles.iter() {
                variant.annotation(format!("#[namespace_role({})]", role));
            }
        }

        namespace.push_variant(variant.to_owned());
    }

    scope.push_enum(namespace);

    scope.raw("// Above is generated by rbac-parser");

    Ok(scope.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse() {
        let result = parse("sports.json");
        assert!(result.is_ok());
        std::fs::write("src/generated.rs", result.unwrap()).unwrap();
    }
}
